# docker-compose.yml
services:
  # 1. Python AI Microservice (the communication is via Flask server)
  ml-service:
    build: 
      context: ./ai_models
    container_name: stock_ml_python
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./ai_models:/app

  # 2. Node.js Main API
  node-backend:
    build: 
      context: .
    container_name: stock_node_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      # docker will take from the .env file those variables 
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      PORT: 3000
      PYTHON_API_URL: "http://ml-service:5000"
    depends_on:
      - ml-service
    # every time that the server is activated run this
    command: sh -c "npx prisma db push && node server.js"