// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // we use direct_url here because when we do migrations we cat to go through the pooling process. we need to get straight to the db
    url: env("DIRECT_URL"),
  },
});