// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma v7 (the version we are using) removed the separate directUrl field - theres now only one "url"
    // used for both migrations and regular app queries. Migrations need a direct
    // (doesnt go through the connection pooling) connection, so we use DIRECT_URL here rather than the pooled
    // DATABASE_URL. At our projects scale, skipping the pooler for normal queries (like changing data)
    // has no real downside
    url: env("DIRECT_URL"),
  },
});